version: '2' 

services:
  portainer:
    image: portainer/portainer
    # https://portainer.readthedocs.io/en/stable/configuration.html#available-flags
    command: ["-H", "unix:///var/run/docker.sock", "--no-analytics"] 
    restart: always
    environment:
      - AGENT_SECRET=${AGENT_SECRET} 
    ports:
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data:/data
