version: "3"

services:
  portainer:
    image: portainer/portainer-ce
    # https://docs.portainer.io/advanced/cli
    command:
      [
        "-H",
        "unix:///var/run/docker.sock",
        "--no-analytics",
       #"--admin-password-file=/data/admin",
      ]
    restart: always
    environment:
      - AGENT_SECRET=${AGENT_SECRET}
    ports:
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data:/data
