version: '3'

services:
  portainer-agent:
    image: portainer/agent
    restart: always
    ports:
      - "9001:9001"
    environment:
      HEALTH_CHECK: "check ssl verify none"
      AGENT_PORT: "9001"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
