version: '3'

services:
  portainer-agent:
    image: portainer/agent
    restart: always
    ports:
      - "9001:9001"
    environment:
      - AGENT_PORT="9001"
      - AGENT_SECRET=${AGENT_SECRET} 
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
